### ISSUE TITLE
xcode 10.2 (10E125) has build error Messaging unqualified id 

### ISSUE THREAD

**Issue by LayMuiToh** [facebookarchive/WebDriverAgent#1099]
At xcode 10.2, open the WebDriverAgent.xcodeproj.
WebDriverAgentLIb -> Generic iOS device
The build fail with the 
Semantic issue: Messaging unqualified id 
FBTCPSocket.m

**Comment by DinukaP19** [comment]
In the project settings xconfig file within the project, add the following: -Wno-everything

**Comment by thinkd1fferent** [comment]
hi @DinukaP19, I tried your suggestion and it built WDA successfully but when I launch Appium.app, it throws the GateKeeper error the the app is damaged and doesn't launch. I'm using Appium 1.8.2 (desktop) with macOS 10.14.4 with Xcode 10.2.

**Comment by DinukaP19** [comment]
@thinkd1fferent have you tried upgrading your Appium desktop?

**Comment by rmirakhur1303** [comment]
@DinukaP19 Yes I did. I've tried macOS 10.14.4 with Appium-Desktop 1.12.1, 1.9.x and 1.8.2 and they all failed with Xcode 10.2

What setup worked reliably for me was: macOS 10.14.4 + Xcode 10.1 + Appium Desktop 1.8.2

I still have issues with CommandLine Appium but as the Desktop version is working, didn't investigate it further. Any pointers on what the problem is and any workaround?

**Comment by thinkd1fferent** [comment]
sorry @DinukaP19, used my work id...its still me answering :)

**Comment by testingxpertshyd** [comment]
Still issue existing on macOS 10.14.4 + Xcode 10.2 + Appium Desktop 1.11.0+ iOS 12.2 Real Device combination. is any workaround there?

**Comment by raoqing** [comment]
Issue existing on  macOS 10.14.4 + Xcode 10.2.1（10E1001） + Appium 1.9.1+ iOS 12.2 Real Device too, seek for help.

**Comment by lijinzhou2016** [comment]
有解吗，在线等

**Comment by Madh93** [comment]
It seems it works with Appium 1.12.1 and some workaround.

**Environment:** macOS 10.14.4 + Xcode 10.2 (10E12) + Appium 1.12.1+ iOS 12.2 Real Device.

1. Go to WebDriverAgent directory: `YOUR_APPIUM_PROJECT/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent`
2. Run: `./Scripts/bootstrap.sh && npm i --package-lock-only && npm audit fix && ./Scripts/bootstrap.sh`
3. Build WebDriverAgent again.

**Comment by Targolo** [comment]
Hi,

I have the exact same issue. Adding -Wno-everything to the .xconfig file helped me build the project from Xcode, but when I start an inspector session from Appium, it builds WebDriverAgent and the error is still appearing.

Running the bootstrap script from the previous post did not help either.

**Comment by Targolo** [comment]
Finally, the workaround to add GCC_TREAT_WARNINGS_AS_ERRORS=0 to the .xconfig file worked for me

**Comment by ritesh2689** [comment]
Using below command over a terminal on path - /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent  can help fix the issue
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' GCC_TREAT_WARNINGS_AS_ERRORS=0 test

Replace <udid> with your device's udid in above command

**Comment by sumeetpanjabi** [comment]
I tried all the above fixes, but my App keeps relaunching again and again. Any help?

**Comment by testingxpertshyd** [comment]
Environment: macOS 10.14.4 + Xcode 10.2 + Appium Desktop 1.11.0+ iOS 12.2 Real Device 
I tried all the above fixes, but my App keeps relaunching again and again. Any help?
please find appium server logs file
[appium-server-logs.txt](https://github.com/facebook/WebDriverAgent/files/3152415/appium-server-logs.txt)

**Comment by ritesh2689** [comment]
> I tried all the above fixes, but my App keeps relaunching again and again. Any help?
> 
> @mykola-mokhnach please help. I was able to build the WebDriverAgent xcode project, but when running test, the app keeps on launching again and again
> 
> Able to launch app using appium desktop v. 1.12.1
> 
> I'm using
> Mac OS: 10.14.4 (18E226)
> Xcode: 10.2.1 (10E1001)
> Appium: 1.13.0
> Real device iOS: 12.2

Any specific reason to move to Appium 1.13.0?

**Comment by sumeetpanjabi** [comment]
@ritesh2689 
I tried with Appium server 1.12.1, facing the same issue. Can you suggest which Appium server version to go with?

**Comment by ritesh2689** [comment]
> @ritesh2689
> I tried with Appium server 1.12.1, facing the same issue. Can you suggest which Appium server version to go with?

Appium Version - 1.12.0
iOS version - iPhone 6s - 12.1 , iPhone 6 - 11.4 (Real Device)
macOS version - 10.14.4
Appium Java Client - 6.1.0
Xcode version - 10.2.1
node version - 10.15.3
npm version - 6.9.0

This is what i am using.

**Comment by sumeetpanjabi** [comment]
@ritesh2689 Okay I will try with Appium 1.12.0

**Comment by testingxpertshyd** [comment]
Any Update on this?

> > @ritesh2689
> > I tried with Appium server 1.12.1, facing the same issue. Can you suggest which Appium server version to go with?
> 
> Appium Version - 1.12.0
> iOS version - iPhone 6s - 12.1 , iPhone 6 - 11.4 (Real Device)
> macOS version - 10.14.4
> Appium Java Client - 6.1.0
> Xcode version - 10.2.1
> node version - 10.15.3
> npm version - 6.9.0
> 
> This is what i am using.

The issue raised with iOS 12.2 version not older versions
iOS version - iPhone 7 - 12.2, iPhone X - 12.2 (Real Device)
@mykola-mokhnach @ritesh2689 Please help me

**Comment by testingxpertshyd** [comment]
> Environment: macOS 10.14.4 + Xcode 10.2 + Appium Desktop 1.11.0+ iOS 12.2 Real Device
> I tried all the above fixes, but my App keeps relaunching again and again. Any help?
> please find appium server logs file
> [appium-server-logs.txt](https://github.com/facebook/WebDriverAgent/files/3152415/appium-server-logs.txt)

Still issue exists. Any fixes?

**Comment by OspreyRen** [comment]
workaround https://github.com/facebookarchive/WebDriverAgent/issues/1093

**Comment by bingguo001** [comment]
Have you solved this problem?

**Comment by riturajkashyap** [comment]
I tried all the above fixes, but my App keeps relaunching again and again. Any help?

@mykola-mokhnach please help. I was able to build the WebDriverAgent xcode project, but when running test, the app keeps on launching again and again

Able to launch app using appium desktop v. 1.9.1

I'm using
Mac OS: 10.14.4 (18E226)
Xcode: 10.2.1 (10E1001)
Appium: 1.9.1
Real device iOS: 11.4
I am still getting the same issue . My app launches and crashes and keeps on launching and crashing in a loop . Please tell me the reason and the solution .
